app:
  file:
    download:
      url: https://loremflickr.com
  number:
    file: 1
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:32769/postgres
    username: postgres
    password: postgrespw
    database: postgresql
  main:
    web-application-type: NONE

logging:
  level:
    root: info
